plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
remote_theme: pmarsceill/just-the-docs
logo: "assets/images/logo-infano.png"

